### ISSUE TITLE
Groups Support

### ISSUE THREAD

**Issue by lucavergantini** [Geolicious/qgis2leaf#199] opened 2015-02-04 15:44 UTC
I've a QGIS project with many groups and sub-groups,

I use the group for a route, for example for a route from A to Z,
I use the sub group for the partial route, for example A-->B, B-->C....Y-->Z and in the sub groups I have a tracks ad a waypoint layer.

Example:
A-->D
   A-->B
      track
      waypoint
   B-->C
      track
      waypoint
   C-->D
      track
      waypoint

The plugin does not permit to handle that situazione,
(I think that it crashes because of the equals layers name).
It would be great if the plugin allow to reflect the groups hierarchy

**Comment by tomchadwin** [comment] 2015-02-04 16:02
Duplicate of #88, although more info on what causes this specific crash would be welcome.

**Comment by tomchadwin** [comment] 2015-03-09 09:50
Closed as duplicate of #88 after no feedback from @lucavergantini - reopen if you have more details.

**Closed by tomchadwin** 2015-03-09 09:50 UTC
Labels: duplicate
