### ISSUE TITLE
Error on creating/exporting  .tif layer

### ISSUE THREAD

**Issue by marcobra** [Geolicious/qgis2leaf#200] opened 2015-02-10 10:39 UTC
Trying to export 2 layers one shape one georeferenced.tif

Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2leaf/qgis2leafdialog.py", line 297, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS, self.selected)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2leaf/qgis2leaf_exec.py", line 507, in qgis2leaf_exec
    dst_ds = driver.CreateCopy( out_raster, src_ds, 0 )
  File "/usr/lib/python2.7/dist-packages/osgeo/gdal.py", line 404, in CreateCopy
    return _gdal.Driver_CreateCopy(self, *args, **kwargs)
ValueError: Received a NULL pointer.

------ My env

Ubuntu 14.04.1 LTS

Versione di QGIS	2.6.1-Brighton	Revisione codice QGIS	exported
Compilato con Qt	4.8.6	Esecuzione con Qt	4.8.6
Compilato con GDAL/OGR	1.11.0	Esecuzione con GDAL/OGR	1.11.0

1.4.1 (in /home/ubuntu/.qgis2/python/plugins/qgis2leaf)

Versione Python:
2.7.6 (default, Mar 22 2014, 23:03:41) 
[GCC 4.8.2]

Versione di QGIS:
2.6.1-Brighton Brighton, exported

I can send PM testing tif file, please tell...

Thank

**Comment by tomchadwin** [comment] 2015-02-10 10:42
Looks like a duplicate of #179 - do you agree, @marcobra?

**Comment by marcobra** [comment] 2015-02-10 11:07
yes

**Comment by marcobra** [comment] 2015-02-10 11:42
Might be related to some requested vars if i have only a tiff file i get and i try to get layer list into plugin i get:

Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2leaf/qgis2leafdialog.py", line 111, in layerGet
    canvas = qgis.utils.iface.mapCanvas()
AttributeError: 'NoneType' object has no attribute 'utils'

**Comment by tomchadwin** [comment] 2015-02-10 11:44
I'm sure this won't help, but did you save your workspace before calling the plugin?

**Comment by marcobra** [comment] 2015-02-10 11:49
Yes, but please ignore previuos post i was trying to debug the python env vars...

**Comment by tomchadwin** [comment] 2015-03-09 09:41
Closed as duplicate of #179

**Closed by tomchadwin** 2015-03-09 09:41 UTC
Labels: duplicate
