### ISSUE TITLE
Layer removes table of contents

### ISSUE THREAD

**Issue by chrishamby** [Geolicious/qgis2leaf#205] opened 2015-03-04 15:02 UTC
I've narrowed it down to a specific shapefile, but I can't work out why adding it to my TOC ends up removing the layer controls, and title elements. 
![image](https://cloud.githubusercontent.com/assets/1383739/6485934/4d74fe5a-c255-11e4-84a2-546512cc4021.png)
In addition, I notice that certain layers end up loading in the new map, even when the option to show no layers is chosen.
![image](https://cloud.githubusercontent.com/assets/1383739/6485872/ddcd41de-c254-11e4-8f6b-ce6572a91632.png)

The rest of my layers (about a dozen) appear to work just fine. Any ideas? I saved the offending file at https://www.dropbox.com/s/8lmpy6qjy14r3ds/projects.zip?dl=0

**Comment by tomchadwin** [comment] 2015-03-05 09:20
The GeoJSON is throwing an error. My suspicion is that this layer is a precise geometry type which qgis2leaf does not yet handle. Let me ask someone who knows about GIS (@edspeth) and get back to you.

**Comment by tomchadwin** [comment] 2015-03-05 14:17
@edspeth and I have confirmed that this happens because some of your features have multiple points. This results in a JS error, crashing the webmap. So, at the moment, we can only handle point layers which are one point per feature (in QGIS terminology, singleparts, not multiparts).

What I don't know is where the limitation lies:

* the plugin code
* the QGIS JSON export which the plugin uses
* Leaflet not supporting this kind of JSON geometry

In the meantime, I don't know whether disaggregating the layer is an option for you (in QGIS: Vector > Geometry Tools > Multipart to Singleparts).

I'll try to work out which of the three possible causes is the actual one and report back.

**Comment by chrishamby** [comment] 2015-03-05 14:48
Thank you for getting back so quickly! That makes sense, and I can disaggregate this layer to create a working map. 

One of my other layers is multipart as well, but with line geometry - that appears to work fine with qgis2leaf.

**Comment by chrishamby** [comment] 2015-03-05 15:32
I also had an issue with unexpected layers appearing in my TOC above, but I'll open a new issue for it.

**Comment by tomchadwin** [comment] 2015-03-09 09:49
Will close this for the moment. We can reopen if someone has a use case when disaggregating is not an option.

**Closed by tomchadwin** 2015-03-09 09:49 UTC
